github:
  is_project_page: false 
  is_user_page: true 
  repository_url: http://mjliu.com 
  
show_downloads: false

author:
  name: M.J.
  url: http://mjliu.com
  
theme: jekyll-theme-hack
title: M.
description: Simplicity is the ultimate sophistication.

google_analytics: UA-50968899-1
